package www.zhaoxinkeji.com.dbdatabase.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import www.zhaoxinkeji.com.dbdatabase.entity.ArticleEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE_ENTITY".
*/
public class ArticleEntityDao extends AbstractDao<ArticleEntity, Void> {

    public static final String TABLENAME = "ARTICLE_ENTITY";

    /**
     * Properties of entity ArticleEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ArticleId = new Property(0, Long.class, "articleId", false, "ARTICLE_ID");
    }


    public ArticleEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE_ENTITY\" (" + //
                "\"ARTICLE_ID\" INTEGER);"); // 0: articleId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ArticleEntity entity) {
        stmt.clearBindings();
 
        Long articleId = entity.getArticleId();
        if (articleId != null) {
            stmt.bindLong(1, articleId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ArticleEntity entity) {
        stmt.clearBindings();
 
        Long articleId = entity.getArticleId();
        if (articleId != null) {
            stmt.bindLong(1, articleId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ArticleEntity readEntity(Cursor cursor, int offset) {
        ArticleEntity entity = new ArticleEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0) // articleId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ArticleEntity entity, int offset) {
        entity.setArticleId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ArticleEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ArticleEntity entity) {
        return null;
    }

    @Override
    public boolean hasKey(ArticleEntity entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
