package www.zhaoxinkeji.com.dbdatabase.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import www.zhaoxinkeji.com.dbdatabase.entity.BaseDataEntity;

import www.zhaoxinkeji.com.dbdatabase.greendao.BaseDataEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseDataEntityDaoConfig;

    private final BaseDataEntityDao baseDataEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseDataEntityDaoConfig = daoConfigMap.get(BaseDataEntityDao.class).clone();
        baseDataEntityDaoConfig.initIdentityScope(type);

        baseDataEntityDao = new BaseDataEntityDao(baseDataEntityDaoConfig, this);

        registerDao(BaseDataEntity.class, baseDataEntityDao);
    }
    
    public void clear() {
        baseDataEntityDaoConfig.clearIdentityScope();
    }

    public BaseDataEntityDao getBaseDataEntityDao() {
        return baseDataEntityDao;
    }

}
